import AuthProvider from '@/providers/AuthProvider'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast'
import './globals.css'


import {
<<<<<<< HEAD
  QueryClient,
  QueryClientProvider,
=======
  QueryClient, QueryClientProvider
>>>>>>> 935d50b36ca5eec22797bed8efc9e119f26bf87a
} from '@tanstack/react-query'

const queryClient = new QueryClient();
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <QueryClientProvider client={queryClient}>

        <AuthProvider>
          <Toaster position="top-center" />
          {children}
        </AuthProvider>
      </QueryClientProvider>
      </body>
    </html>
  )
}
